create table user (
	userID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(255),
	fullname VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);

create table account (
	accID VARCHAR(255) PRIMARY KEY,
	description VARCHAR(255) NOT NULL,
	balance BIGINT NOT NULL,
	max_balance BIGINT NOT NULL
);

create table customer_account (
	userID INTEGER,
	accID VARCHAR(255),
	PRIMARY KEY(userID, accID) 
);

create table account_transaction (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	from_account_number VARCHAR(255),
	to_account_number VARCHAR(255),
	amount  BIGINT NOT NULL,
	time datetime NOT NULL
);